### PR TITLE
Must not include pure-C header without `extern "C"` in C++

### PR DESCRIPTION
**Pull request by marcusmueller**
Fixes unbuildability on most compilers

### CODE REVIEW

**Comment by kantooon** [comment]
Something is strange here: the gsm.h in Debian contains

    #ifdef __cplusplus
    extern "C" {
    #endif

**Comment by dkozel** [comment]
I was able to build without this change, GCC 7.2.0 on Ubuntu 17.10.

**Comment by kantooon** [comment]
I'm not sure what exactly is happening here, but I think it should probably be investigated on the distro side.

**Comment by kantooon** [comment]
It seems other distributions ship the gsm.h header without including this. So this is merged now.

**Pull request closed without merging**
