### PR TITLE
use pkgconfig for qwt includes

### PR DESCRIPTION
**Pull request by ZeroChaos-**
qt4 is dead and removed from modern distros, safe to remove from git
version.
use pkgconfig to find includes et al for qwt
fixes issue #26

### CODE REVIEW

**Comment by kantooon** [comment]
Thanks. Looks good but won't work on other distros. Qt4 is still needed on Debian stable so I'll keep this pull request open for now if you don't mind.
Not sure what Gentoo does with GNU radio and Qt dependencies, but if you want to package it have a look at https://build.opensuse.org/package/show/hardware:sdr/qradiolink
I've no problem if you want to patch the project file downstream.

**Comment by ZeroChaos-** [comment]
I can include the qt4 stuff if you like, but seeing as how it's dead and being removed by debian that seems like the biggest waste of time travel I can think of:
https://wiki.debian.org/Qt4Removal

That said, if it will make you accept my patch, I'll add the proper stuff to make it work for the qt version that every distro is removing....

**Comment by kantooon** [comment]
In fact, the more I think about it, the more it looks to me like the GNU radio maintainer for $DISTRO might need to manually patch the GNU radio headers to look at the correct include path. I'm not including qwt_symbol.h directly in qradiolink, GNU radio does. Here's the offending include in /usr/include/gnuradio/qtgui/sink_c.h
``#include <qwt_symbol.h>``
As you can see, it's looking for it in /usr/include or /usr/local/include or whatever.

**Comment by ZeroChaos-** [comment]
As requested, this linked against either qt4 or qt5.  I lack the ability to test on qt4, but it does work on qt5.  Please accept.

**Comment by kantooon** [comment]
This is no longer needed.

**Pull request closed without merging**
